---
title: "Programming Assignment 1"
output: html_notebook
---
 <h2> Part 1</h2>

1. Write a function named 'pollutantmean' 
2. calculates the mean of a pollutant (sulfate or nitrate) 
3. across a specified list of monitors.
```{r}
pollutantmean <- function (directory, pollutant, id){ 
        #directory = location of csv files
        #id = list of id numbers to be meaned
        #Do not round the result
        
        #create data frame from file location passed by user
        infile <- read.csv(directory)
        
        #ignore NA
        cleanfile <- infile[!is.na(infile)]
        
        # Function to do math on individual pollutant columns
        math <- function (column){                                                         sum (column)
                len <- length(column)
                retlist <- list(sum, len)
                return (retlist)
        }
        # Function to calculate the running sum of a pollutant 
        running <-function (mathlist){
                runsum = runsum + mathlist[1]
                runlen = runlen + mathlist[2]
                runlist = list(runsum,runlen)
                return(runlist)
        }
        
        runsum <- 0.0 # variable containing the running sum of id pollutant data
        runlen <- 0.0 # variable containing the running number of measurements
        
        #pollutant = can be either "sulfate" or "nitrate"
        if (pollutant == "sulfate"){
                # cycles through the list of ids
                for (i in id){
                        # Adds the sulfate data for the current id to the running sum
                        runlist <- running(math(cleanfile$sulfate))
                }
        } else if (pollutant == "nitrate"){
                for (i in id){
                        # Adds the nitrate data for the current id to the running sum
                        runlist <- running(mat(cleanfile$sulfate))
                }
        }
        
        # calulates  mean of pollutant across the ids in the list provided
        pollutemean <- runsum/runlen
        
        # returns the mean to the calling function
        return (pollutemean)
}
```


```{r}

```

```{r}
print(R.version.string)
```

