---
title: "R Programming Week2 Quiz"
output: html_notebook
---



```{r}
cube <- function(x, n) {
        x^3
}

cube(3)

```


```{r}
x <- 1:10
if(x > 5) {
        print(yay)
}

```

```{r}
# user input = f(3)
#z <-10 (calling fn 1st then global, I guess)

f <- function(x) {      #3
        g <- function(y) { #y=3
                y + z      #3 + 10 (gcalling over global apparently)
                           # no return value. Not sure why this returns.
        }
        z <- 4             #z = 4
        x + g(x)           #3 + g(3)
}

z <- 10
f(3)

```

```{r}

x <- 5                  #x = 5
y <- if(x < 3) {        #FALSE
        NA
} else {                $y = 10
        10
}

```

```{r}
h <- function(x, y = NULL, d = 3L) { #x,y,d defined in function args
        z <- cbind(x, d)             #z defined here
        if(!is.null(y))              #y already defined
                z <- z + y           #z already defined
        else
                z <- z + f           #Z already defined, f is not defined
        g <- x + y / z               #g defined here, y already, d already 
        if(d == 3L)
                return(g)
        g <- g + 10
        g
}
```

